### PR TITLE
Fixes #94

### LINKED ISSUE #94: Body matcher fails due to regex matching
I have a static scenario with "record". When trying to match them with mode.ENABLED, I get an exception :
```
ERROR fr.speekha.httpmocker.scenario.StaticMockProvider - Scenario file could not be loaded
java.util.regex.PatternSyntaxException: Illegal repetition
{"data":{"username":"XXX","key":"XXX","project_code":"Explorers_Helidon"},"action":"get_information","group":"projects"}
	at java.util.regex.Pattern.error(Pattern.java:1969) ~[?:1.8.0_265]
	at java.util.regex.Pattern.closure(Pattern.java:3171) ~[?:1.8.0_265]
	at java.util.regex.Pattern.sequence(Pattern.java:2148) ~[?:1.8.0_265]
	at java.util.regex.Pattern.expr(Pattern.java:2010) ~[?:1.8.0_265]
	at java.util.regex.Pattern.compile(Pattern.java:1702) ~[?:1.8.0_265]
	at java.util.regex.Pattern.<init>(Pattern.java:1352) ~[?:1.8.0_265]
	at java.util.regex.Pattern.compile(Pattern.java:1028) ~[?:1.8.0_265]
	at kotlin.text.Regex.<init>(Regex.kt:89) ~[kotlin-stdlib-1.4.10.jar:1.4.10-release-411 (1.4.10)]
	at fr.speekha.httpmocker.io.OkHttpExtensionsKt.matchBody(OkHttpExtensions.kt:46) ~[mocker-1.2.0.jar:?]
	at fr.speekha.httpmocker.scenario.RequestMatcher.matchBody(RequestMatcher.kt:37) ~[mocker-1.2.0.jar:?]
```

**To Reproduce**

Create a static scenario with :
```
{
  "request" : {
    "method" : "POST",
    "headers" : { },
    "params" : { },
    "body" : "{\"data\":{\"username\":\"XXX\",\"key\":\"XXX\",\"project_code\":\"Explorers_Helidon\"},\"action\":\"get_information\",\"group\":\"projects\"}"
  },
```

**Expected behavior**
Of course the body section of a request is meant to be a regex, but a recorded scenario should be matched "out of the box" to minimize work for the developer.
**I experimented a little and an easy solution would be to create the regex in OkHttpExtensions.kt:44 :**
`Regex(bodyPattern, RegexOption.LITERAL)`, but then normal regex would not work anymore :(

**Desktop (please complete the following information):**
httpmocker version 1.2.0
Kotlin version 1.4
Retrofit version 2.9.0
OkHttp version 4.8.1

### PR DESCRIPTION
**Pull request by speekha**
Saves request body as a parsable regex when recording a scenario

### CODE REVIEW

File: tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt [hunk 1]
```diff
@@ -263,7 +252,7 @@
~        @MethodSource("fr.speekha.httpmocker.interceptor.TestWithServer#mappers")
```
Comment (speekha) [inline tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt]: Codacy found an issue: [Indentation - [] at /src/tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt:513:1](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648)

**Comment by speekha** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648&bid=20513800)

File: tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt [hunk 2]
```diff
@@ -283,7 +272,7 @@
...
~        @DisplayName(
~            "When recording a request for a URL ending with a '/', " +
~                    "then scenario files should be named with 'index'"
~        )
```
Comment (speekha) [inline tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt]: Codacy found an issue: [Indentation - [] at /src/tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt:525:23](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648)

File: mocker/src/main/kotlin/fr/speekha/httpmocker/io/OkHttpExtensions.kt [hunk 3]
```diff
@@ -19,13 +19,7 @@
...
 import fr.speekha.httpmocker.model.RequestDescriptor
 import fr.speekha.httpmocker.model.ResponseDescriptor
-import okhttp3.Headers
-import okhttp3.HttpUrl
-import okhttp3.Interceptor
-import okhttp3.Request
-import okhttp3.RequestBody
-import okhttp3.Response
-import okhttp3.ResponseBody
+import okhttp3.*
```
Comment (speekha) [inline mocker/src/main/kotlin/fr/speekha/httpmocker/io/OkHttpExtensions.kt:22]: Codacy found an issue: [WildcardImport - [OkHttpExtensions.kt] at /src/mocker/src/main/kotlin/fr/speekha/httpmocker/io/OkHttpExtensions.kt:22:1](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648)

**Comment by speekha** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 2
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648&bid=20513800)

File: tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt (hunk 1 above)
Comment (speekha) [inline tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt]: Codacy found an issue: [Indentation - [] at /src/tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt:513:1](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648)

File: tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt (hunk 2 above)
Comment (speekha) [inline tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt]: Codacy found an issue: [Indentation - [] at /src/tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt:525:23](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648)

**Comment by speekha** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648&bid=20513800)

File: tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt [hunk 4]
```diff
@@ -516,6 +519,34 @@ class RecordTests : TestWithServer() {
...
+            title: String,
+            mapper: Mapper,
+            fileType: String
+        ) {
+            enqueueServerResponse(200, "body")
+            setUpInterceptor(mapper, fileType = fileType)
+            executeRequest(
+                url = recordRequestUrl,
+                method = "POST",
+                body = """{"some Json content": "some random value"}"""
```
Comment (speekha) [inline tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt:539]: Codacy found an issue: [Indentation - [] at /src/tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt:525:23](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648)

**Comment by speekha** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 9
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648&bid=20513800)

File: tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt (hunk 4 above)
Comment (speekha) [inline tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt:539]: Codacy found an issue: [Indentation - [] at /src/tests/src/test/kotlin/fr/speekha/httpmocker/interceptor/RecordTests.kt:525:23](https://app.codacy.com/manual/speekha/httpmocker/pullRequest?prid=6308648)
